import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import { ClientProviders } from '@/components/client-providers'
import { NextIntlClientProvider } from 'next-intl'
import './globals.css'
import { getMessages } from 'next-intl/server'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'MPost',
    description: 'Generated by maciel',
}

type RootLayoutProps = {
    children: React.ReactNode
    params: Promise<{ locale: string }>
}

export default async function RootLayout({
    children,
    params,
}: RootLayoutProps) {
    const { locale } = await params
    const messages = await getMessages()

    return (
        <html
            lang={locale}
            className="overflow-x-hidden"
            suppressHydrationWarning
        >
            <body
                className={`${geistSans.className} min-h-screen overflow-x-hidden relative antialiased`}
            >
                <NextIntlClientProvider messages={messages}>
                    <ClientProviders>{children}</ClientProviders>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
