import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/providers/theme-provider'
import { SessionProvider } from 'next-auth/react'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'MPost',
    description: 'Generated by maciel',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            lang="pt-br"
            className="overflow-x-hidden"
            suppressHydrationWarning
        >
            <body
                className={`${geistSans.className} min-h-screen overflow-x-hidden relative antialiased`}
            >
                <SessionProvider>
                    <ThemeProvider
                        attribute="class"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                    </ThemeProvider>
                </SessionProvider>
            </body>
        </html>
    )
}
